### PR TITLE
Emit IndirectImports and UnknownFunctions lints.

### PR DESCRIPTION
**Pull request by m-kostrzewa**

### CODE REVIEW

**Comment by krdln** [comment]
I'd like to merge it as is, but please rename the commit.

**Comment by m-kostrzewa** [comment]
@krdln I think it can be renamed while merging?

**Comment by krdln** [comment]
Yeah, it could be done when doing squash'n'merge, but I prefer not to. But whatevs.

**Comment by m-kostrzewa** [comment]
@krdln k tomorrow then

**Pull request merged**
